name: Update Warehouse Chart
on:
  push:
    paths:
      - 'magazyn.csv'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas plotly  # Zmieniono z matplotlib na plotly
      - name: Generate Chart
        run: python generate_chart.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Aktualizacja interaktywnego wykresu" || exit 0
          git push
